title: Руководство по Git
email: katyunya.aleksandrovna.97@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Руководство представлено исключительно как портфолио.
baseurl: "primery" # the subpath of your site, e.g. /blog
url: "https://Ekaterinka17.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kettic17
github_username: Ekaterinka17
  
# Build settings
markdown: GFM
plugins:
  - jekyll-gfm-admonitions

include:
  - README.md
exclude:
  - sample/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
permalink: /:year/:title:output_ext
theme: minima
