title: Руководство по Git
email: katyunya.aleksandrovna.97@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  В руководстве по Git приведено описание по установке, развертыванию и
  использованию данного инструмента техническим писателем.
baseurl: "primery" # the subpath of your site, e.g. /blog
url: "https://Ekaterinka17.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kettic17
github_username: Ekaterinka17
  
# Build settings
markdown: GFM
plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

exclude: 
  - "**/*.ts" # Exclude source code files!
  - "**/*.js"
  - "*.ts" # Also those in the root directory!
  - "*.js"
  - "*.json" # Don't forget about assets!
  - node_modules/ # And large vendored directories
  # And these ignore all the artifacts the build produces:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
permalink: /:title:output_ext
theme: minima
